/*
 * generated by Xtext
 */
package de.redoxi.ruste.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractRustValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.redoxi.ruste.rust.RustPackage.eINSTANCE);
		return result;
	}
}
