/*
* generated by Xtext
*/
package de.redoxi.ruste;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RustStandaloneSetup extends RustStandaloneSetupGenerated{

	public static void doSetup() {
		new RustStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

