/*
 * generated by Xtext
 */
package de.redoxi.ruste.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.redoxi.ruste.ui.internal.RustActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RustExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RustActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RustActivator.getInstance().getInjector(RustActivator.DE_REDOXI_RUSTE_RUST);
	}
	
}
