/*
* generated by Xtext
*/
package de.redoxi.ruste.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.redoxi.ruste.services.RustGrammarAccess;

public class RustParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RustGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.redoxi.ruste.parser.antlr.internal.InternalRustParser createParser(XtextTokenStream stream) {
		return new de.redoxi.ruste.parser.antlr.internal.InternalRustParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Crate";
	}
	
	public RustGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RustGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
