/*
* generated by Xtext
*/
package de.redoxi.ruste;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RustUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.redoxi.ruste.ui.internal.RustActivator.getInstance().getInjector("de.redoxi.ruste.Rust");
	}
	
}
